### ISSUE TITLE
LIDC-IDRI Data Generator Issue

### ISSUE THREAD

**Issue by deepkaneria** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#15]
Hey there!
When trying to generate the preprocessed_data for testing from the LIDC-IDRI dataset using the prepareLIDC.py it throughs the following errors. I tried hard but was not able to solve it.  Thanks a lot in advance

starting preprocessing
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/deep.int022/anaconda3/envs/dp_env_gpu/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/deep.int022/anaconda3/envs/dp_env_gpu/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "lidcnew.py", line 79, in savenpy
    box = np.array([[np.min(xx),np.max(xx)],[np.min(yy),np.max(yy)],[np.min(zz),np.max(zz)]])
  File "/home/deep.int022/anaconda3/envs/dp_env_gpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2618, in amin
    initial=initial)
  File "/home/deep.int022/anaconda3/envs/dp_env_gpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lidcnew.py", line 155, in <module>
    full_prep()
  File "lidcnew.py", line 149, in full_prep
    _=pool.map(partial_savenpy,range(N))
  File "/home/deep.int022/anaconda3/envs/dp_env_gpu/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/deep.int022/anaconda3/envs/dp_env_gpu/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by ymli39** [comment]
I think this means the one of the xx,yy,zz is zero size array to cause the error? I used python 0.4.0 for running this code, this might be caused by different python version?
I cleaned up my server since last summer, so I do not have data in hand to test...

**Comment by deepkaneria** [comment]
> I think this means the one of the xx,yy,zz is zero size array to cause the error? I used python 0.4.0 for running this code, this might be caused by different python version?
> I cleaned up my server since last summer, so I do not have data in hand to test...

Yes, you are correct the xx, yy, zz all the three returns null values, and that's the reason behind the error, I am trying to downgrade to your preferred version but haven't succeeded yet, as there are multiple dependencies conflicting each other.

If anyone else does have a solution or an edit LIDC generator, Any help will be appreciated.

Thank You!!

**Comment by MjdMahasneh** [comment]
@deepkaneria Could you give an update on what versions did you end up using? What torch CUDA cuDNN and python versions, please? That would be very helpful and very much appreciated.
