### ISSUE TITLE
Nodule Detection Errors

### ISSUE THREAD

**Issue by ghost** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#20]
Hi @ymli39 
I am facing a starnge error when I am training the detector network. Do you have any comment on this error?

Traceback (most recent call last):
  File "/home/sh/Documents/Codes/My_Models/My_Seed/luna_detector/train_detector_se.py", line 351, in <module>
    main()
  File "/home/sh/Documents/Codes/My_Models/My_Seed/luna_detector/train_detector_se.py", line 159, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, save_dir)
  File "/home/sh/Documents/Codes/My_Models/My_Seed/luna_detector/train_detector_se.py", line 187, in train
    for i, (data, target, coord) in enumerate(data_loader):
  File "/home/sh/Documents/Codes/DSB2017-master/venv/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/sh/Documents/Codes/DSB2017-master/venv/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/sh/Documents/Codes/DSB2017-master/venv/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/sh/Documents/Codes/DSB2017-master/venv/local/lib/python2.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 29.
Original Traceback (most recent call last):
  File "/home/sh/Documents/Codes/DSB2017-master/venv/local/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sh/Documents/Codes/DSB2017-master/venv/local/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    print(possibly_batched_index)
  File "/home/sh/Documents/Codes/My_Models/My_Seed/luna_detector/data_loader.py", line 108, in __getitem__
    label = self.label_mapping(sample.shape[1:], target, bboxes)
  File "/home/sh/Documents/Codes/My_Models/My_Seed/luna_detector/data_loader.py", line 286, in __call__
    assert (input_size[i] % stride == 0)
AssertionError

**Comment by KinaTech** [comment]
Hello, Did you solve this problem? I have the same error? 
@ymli39 Do you have any idea about this error?

**Comment by KinaTech** [comment]
It seems that the problem is in this line:
assert (input_size[i] % stride == 0)
I tired to skip this assert but the point is that when model tries to calculate the dz it face some difficulties. 
  label = self.label_mapping(sample.shape[1:], target, bboxes)
  File "/home/Seed/luna_detector/data_loader.py", line 335, in __call__
  dz = (target[0] - oz[pos[0]]) / anchors[pos[3]]
  IndexError: index 6 is out of bounds for axis 0 with size 1
@ymli39 Do you have any comment?
